version: '3'

services:
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      - DB_USER=postgres
      - DB_PASS=crudjs
  adminer:
    image: adminer
    restart: always
    ports:
        - 8080:8080
