Vagrant.configure("2") do |config|
  config.vm.box = "debian/stretch64"
  config.vm.network "private_network", ip: "10.0.120.10"
  config.vm.hostname = "jenkins.deb"
  config.vm.provision "ansible" do |ansible|
    ansible.become = true
    ansible.galaxy_role_file = "provision/requirements.yml"
    ansible.playbook = "provision/main.yml"
  end
end
